cmake_minimum_required(VERSION 3.8)
project(prometheus_control)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_python REQUIRED)
find_package(prometheus_msgs REQUIRED)
find_package(wksim_msgs REQUIRED)
ament_python_install_package(${PROJECT_NAME})
install(PROGRAMS scripts/prometheus_control_node DESTINATION lib/${PROJECT_NAME})
ament_export_dependencies(prometheus_msgs wksim_msgs)
ament_package()
