# Copyright 2022 AMOVLAB. SPDX-License-Identifier: Apache-2.0
# wksim ROS2 migration of Prometheus 5dcd8cfa764d: GetLocationSource.srv.
# Naming/type aliases changed; see UPSTREAM.json. Original comments retained.
---
# 是否获取成功
bool success
# 如果失败反馈提示
string message
uint8[] location_source
string[] location_source_name
