#!/usr/bin/env python3
"""Generate synthetic perf switch-stream fixtures for independent acceptance.

Source of truth: docs/coordination/perf-stream-contract-20260913.md (frozen contract).
This script does NOT import, read or mirror any consumer/producer implementation: the
binary records are built directly with `struct` from the contract's byte definition
(header8 + TID/TIME/CPU24 = exact 32-byte SWITCH records, little-endian x86_64).

Every fixture is explicitly synthetic: metadata carries `synthetic=true` +
`synthetic_note`, and no fixture describes a real flight.

Usage:
    python build_fixtures.py            # write fixtures + index (deterministic)
    python build_fixtures.py --check    # re-decode what is on disk, re-assert expected.json

Outputs are pure Python + stdlib; nothing here compiles, schedules or touches native.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures")

# --- contract enums (public perf_event ABI values, little-endian x86_64) -----------------
PERF_RECORD_LOST = 2
PERF_RECORD_LOST_SAMPLES = 13
PERF_RECORD_SWITCH = 14
PERF_RECORD_SWITCH_CPU_WIDE = 15
MISC_SWITCH_OUT = 1 << 13      # PERF_RECORD_MISC_SWITCH_OUT
MISC_SWITCH_OUT_PREEMPT = 1 << 14
RECORD_SIZE = 32                # header8 + TID/TIME/CPU24, exact per contract
HEADER = struct.Struct("<IHH")
SWITCH_BODY = struct.Struct("<IIQII")

CLOCK_ID = "CLOCK_MONOTONIC"
SWITCH_SCHEMA = "wksim.perf_switch_stream.v1"
WINDOWS_SCHEMA = "wksim.perf_windows.v1"
OWNER_PID = 7331
OWNER_TID = 7333
FOREIGN_TID = 9999
BOOT_A = "11111111-2222-4333-8444-555555555555"
BOOT_B = "99999999-8888-4777-8666-555555555555"

# Outer capture bounds; every raw timestamp in every fixture lies inside them.
ENABLE_BEFORE_NS = 900_000
ENABLE_AFTER_NS = 950_000
DISABLE_BEFORE_NS = 9_900_000
DISABLE_AFTER_NS = 9_950_000
RING_BYTES = 128 * 4096
STORAGE_CAPACITY_BYTES = 128 * 1024 * 1024


# --- raw record construction (pure struct; no producer code involved) -------------------
def record(kind=PERF_RECORD_SWITCH, misc=0, tid=OWNER_TID, time_ns=0, cpu=0,
           size=RECORD_SIZE):
    """One raw perf record: header(type,misc,size) + TID/TIME/CPU/res."""
    body = SWITCH_BODY.pack(OWNER_PID, tid, time_ns, cpu, 0)
    if kind == PERF_RECORD_LOST:
        body = struct.pack("<QQ", 7, 2093) + body
        size = 8 + len(body)
    elif kind == PERF_RECORD_LOST_SAMPLES:
        body = struct.pack("<Q", 5) + body
        size = 8 + len(body)
    elif kind == PERF_RECORD_SWITCH_CPU_WIDE:
        body = struct.pack("<II", 9999, 0) + body
        size = 8 + len(body)
    return HEADER.pack(kind, misc, size) + body


def out(time_ns, tid=OWNER_TID, cpu=0):
    return record(misc=MISC_SWITCH_OUT, tid=tid, time_ns=time_ns, cpu=cpu)


def into(time_ns, tid=OWNER_TID, cpu=0):
    return record(misc=0, tid=tid, time_ns=time_ns, cpu=cpu)


def raw(*records):
    return b"".join(records)


def metadata(captured_bytes, *, complete=True, errors=(), owner_pid=OWNER_PID,
             owner_tid=OWNER_TID, boot_id=BOOT_A, clock_id=CLOCK_ID, **overrides):
    meta = {
        "schema": SWITCH_SCHEMA,
        "classification": "diagnostic_only",
        "full_acceptance": False,
        "synthetic": True,
        "synthetic_note": ("generated by build_fixtures.py; not flight evidence; see "
                           "docs/coordination/perf-stream-contract-20260913.md"),
        "owner_pid": owner_pid,
        "owner_tid": owner_tid,
        "boot_id": boot_id,
        "clock_id": clock_id,
        "enable_before_ns": ENABLE_BEFORE_NS,
        "enable_after_ns": ENABLE_AFTER_NS,
        "disable_before_ns": DISABLE_BEFORE_NS,
        "disable_after_ns": DISABLE_AFTER_NS,
        "ring_bytes": RING_BYTES,
        "storage_capacity_bytes": STORAGE_CAPACITY_BYTES,
        "captured_bytes": captured_bytes,
        "reader_policy": 0,             # Linux SCHED_OTHER as a plain int, never a string
        "config": {
            "pid_argument": 0,
            "cpu_argument": -1,
            "inherit": 0,
            "exclude_kernel": 1,
            "context_switch": 1,
            "sample_id_all": 1,
            "sample_type": ["TID", "TIME", "CPU"],
        },
        "collector_complete": complete,
        "collector_errors": list(errors),
        "lifecycle": {
            "disable_ok": True,
            "reader_joined": True,
            "munmap_ok": True,
            "close_ok": True,
        },
    }
    meta.update(overrides)
    return meta


def windows(entries, *, boot_id=BOOT_A, owner_pid=OWNER_PID, owner_tid=OWNER_TID,
            clock_id=CLOCK_ID, **overrides):
    doc = {
        "schema": WINDOWS_SCHEMA,
        "synthetic": True,
        "boot_id": boot_id,
        "owner_pid": owner_pid,
        "owner_tid": owner_tid,
        "clock_id": clock_id,
        "windows": [{"id": str(i), "start_ns": s, "end_ns": e}
                    for i, (s, e) in enumerate(entries)],
    }
    doc.update(overrides)
    return doc


# --- fixture bodies ----------------------------------------------------------------------
P0_OUT, P0_IN = 1_000_000, 1_250_000
P1_OUT, P1_IN = 2_000_000, 2_300_000
NORMAL_RAW = raw(out(P0_OUT), into(P0_IN), out(P1_OUT), into(P1_IN))

# Exact integer intersections: w0 -> 150_000 inside pair0; w1 -> 0 (wholly in the gap
# between pairs); w2 -> 50_000 from pair0 + 50_000 from pair1 = 100_000.
INTERSECT_WINDOWS = ((1_000_000, 1_150_000), (1_300_000, 1_350_000), (1_200_000, 2_050_000))
INTERSECT_EXPECTED_NS = (150_000, 0, 100_000)

OTHER_BOOT_WINDOWS = ((1_000_000, 1_150_000), (2_000_000, 2_100_000))
OTHER_BOOT_EXPECTED_NS = (150_000, 100_000)


def case_normal_two_pairs():
    return dict(raw=NORMAL_RAW, meta=metadata(len(NORMAL_RAW)),
                windows=windows(INTERSECT_WINDOWS),
                expected={"rejected": False, "checksum_ok": True, "errors": [], "pairs": 2,
                          "intersections_ns": list(INTERSECT_EXPECTED_NS)})


def case_window_intersection_integers():
    return dict(raw=NORMAL_RAW, meta=metadata(len(NORMAL_RAW)),
                windows=windows(INTERSECT_WINDOWS),
                expected={"rejected": False, "checksum_ok": True, "errors": [], "pairs": 2,
                          "intersections_ns": [150_000, 0, 100_000],
                          "intersection_note": ("cross-window exact integers; window 1 is a true "
                                                "empty intersection and must not be dropped")})


def case_foreign_tid():
    body = raw(out(P0_OUT), into(P0_IN, tid=FOREIGN_TID), out(P1_OUT), into(P1_IN))
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True, "errors": ["foreign_tid"],
                          "pairs": 0})


def case_lost():
    body = raw(out(P0_OUT), into(P0_IN),
               record(kind=PERF_RECORD_LOST, tid=OWNER_TID, time_ns=1_900_000),
               out(P1_OUT), into(P1_IN))
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["lost_record"], "pairs": 0})


def case_lost_samples():
    body = raw(out(P0_OUT), into(P0_IN),
               record(kind=PERF_RECORD_LOST_SAMPLES, tid=OWNER_TID, time_ns=1_900_000),
               out(P1_OUT), into(P1_IN))
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["lost_samples_record"], "pairs": 0})


def case_zero_and_backwards_time():
    # pair0 is zero-length (out and in at the same ns); pair1's in precedes its out.
    body = raw(out(P0_OUT), into(P0_OUT), out(P1_OUT), into(P1_OUT - 100_000))
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["nonincreasing_time", "zero_length_span"], "pairs": 0})


def case_double_out():
    # Second switch-out while one is already open, and a second switch-in with nothing
    # open: both orderings violate out/in alternation.
    body = raw(out(P0_OUT), out(P0_OUT + 100_000), into(P0_IN), into(P0_IN + 100_000))
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["unpaired_in", "unpaired_out"],
                          "pairs": 0})


def case_trailing_out():
    body = raw(out(P0_OUT), into(P0_IN), out(P1_OUT))
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["unpaired_out"], "pairs": 0})


def case_truncated():
    body = out(P0_OUT)[:24]           # header claims 32 bytes, only 24 are present
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["truncated_record"], "pairs": 0})


def case_unknown_record_type():
    body = raw(out(P0_OUT), into(P0_IN),
               record(kind=PERF_RECORD_SWITCH_CPU_WIDE, tid=OWNER_TID, time_ns=1_900_000),
               out(P1_OUT), into(P1_IN))
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["unknown_record_type"], "pairs": 0})


def case_malformed_record_size():
    # Declared size 24 is not the exact 32-byte switch record.
    body = HEADER.pack(PERF_RECORD_SWITCH, MISC_SWITCH_OUT, 24) + out(P0_OUT)[8:]
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["malformed_record_size"], "pairs": 0})


def case_illegal_preempt_on_in():
    # SWITCH_OUT_PREEMPT is illegal on a switch-in, independently of pairing.
    body = raw(out(P0_OUT), record(misc=MISC_SWITCH_OUT_PREEMPT, time_ns=P0_IN))
    return dict(raw=body, meta=metadata(len(body)),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["illegal_preempt_on_in"], "pairs": 0})


def case_raw_length_mismatch():
    # Records decode cleanly and form two pairs; the metadata byte count is wrong.
    return dict(raw=NORMAL_RAW, meta=metadata(len(NORMAL_RAW) + 8),
                expected={"rejected": True, "checksum_ok": False,
                          "errors": ["raw_length_mismatch"], "pairs": 0})


def case_false_complete_flag():
    return dict(raw=NORMAL_RAW, meta=metadata(len(NORMAL_RAW), complete=False),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["collector_incomplete"], "pairs": 0})


def case_collector_errors():
    errors = [{"stage": "drain", "errno": 5, "detail": "EIO while copying wrapped bytes"}]
    return dict(raw=NORMAL_RAW,
                meta=metadata(len(NORMAL_RAW), complete=False, errors=errors),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["collector_errors", "collector_incomplete"], "pairs": 0})


def case_other_boot_windows():
    return dict(raw=NORMAL_RAW, meta=metadata(len(NORMAL_RAW)),
                windows=windows(OTHER_BOOT_WINDOWS, boot_id=BOOT_B),
                expected={"rejected": True, "checksum_ok": True,
                          "errors": ["windows_boot_mismatch"], "pairs": 0,
                          "intersections_ns": list(OTHER_BOOT_EXPECTED_NS)})


def case_bool_as_int():
    # Python bools are ints; these fields must be rejected as the wrong type. Because the
    # declared byte count is not a usable integer, the length cross-check cannot pass.
    meta = metadata(len(NORMAL_RAW))
    meta["owner_tid"] = True
    meta["captured_bytes"] = True
    return dict(raw=NORMAL_RAW, meta=meta,
                expected={"rejected": True, "checksum_ok": False,
                          "errors": ["captured_bytes_not_int", "foreign_tid",
                                     "owner_tid_not_int"],
                          "pairs": 0})


CASES = (
    ("normal_two_pairs", case_normal_two_pairs),
    ("window_intersection_integers", case_window_intersection_integers),
    ("foreign_tid", case_foreign_tid),
    ("lost", case_lost),
    ("lost_samples", case_lost_samples),
    ("zero_and_backwards_time", case_zero_and_backwards_time),
    ("double_out", case_double_out),
    ("trailing_out", case_trailing_out),
    ("truncated", case_truncated),
    ("unknown_record_type", case_unknown_record_type),
    ("malformed_record_size", case_malformed_record_size),
    ("illegal_preempt_on_in", case_illegal_preempt_on_in),
    ("raw_length_mismatch", case_raw_length_mismatch),
    ("false_complete_flag", case_false_complete_flag),
    ("collector_errors", case_collector_errors),
    ("other_boot_windows", case_other_boot_windows),
    ("bool_as_int", case_bool_as_int),
)

ASSERT_KEYS = ("rejected", "checksum_ok", "pairs", "errors", "intersections_ns")


def digest(data):
    return hashlib.sha256(data).hexdigest()


def generate():
    # Only rewrite known generated files; never recursively delete an output directory.
    os.makedirs(FIXTURES, exist_ok=True)
    index = {
        "schema": "wksim.perf_stream_fixture_index.v1",
        "synthetic": True,
        "synthetic_note": "all fixtures are generated; none is flight evidence",
        "contract": "docs/coordination/perf-stream-contract-20260913.md",
        "generator": "build_fixtures.py",
        "owner_pid": OWNER_PID,
        "owner_tid": OWNER_TID,
        "cases": [],
    }
    for name, builder in CASES:
        case = builder()
        target = os.path.join(FIXTURES, name)
        os.makedirs(target, exist_ok=True)
        files = {"raw.bin": case["raw"],
                 "metadata.json": (json.dumps(case["meta"], indent=2, sort_keys=True) + "\n").encode()}
        if "windows" in case:
            files["windows.json"] = (json.dumps(case["windows"], indent=2,
                                                sort_keys=True) + "\n").encode()
        files["expected.json"] = (json.dumps(case["expected"], indent=2,
                                             sort_keys=True) + "\n").encode()
        entry = {"case": name, "files": {}}
        for filename in sorted(files):
            with open(os.path.join(target, filename), "wb") as stream:
                stream.write(files[filename])
            entry["files"][filename] = {"sha256": digest(files[filename]),
                                        "bytes": len(files[filename])}
        index["cases"].append(entry)
    with open(os.path.join(FIXTURES, "index.json"), "w", encoding="utf-8") as stream:
        stream.write(json.dumps(index, indent=2, sort_keys=True) + "\n")
    return index


# --- independent re-decode of the written fixtures (contract rules only) -----------------
def decode(data):
    """Walk the raw stream. Returns (records, errors, spans).

    Forbidden record kinds are recorded and skipped (so much later records are still
    examined); a wrong declared size aborts, because no further boundary is trustworthy.
    """
    records, errors, spans, offset, open_out = [], [], [], 0, None
    while offset < len(data):
        if len(data) - offset < 8:
            errors.append("truncated_header")
            break
        kind, misc, size = HEADER.unpack_from(data, offset)
        if len(data) - offset < size:
            errors.append("truncated_record")
            break
        if kind == PERF_RECORD_SWITCH and size != RECORD_SIZE:
            errors.append("malformed_record_size")
            break
        if kind == PERF_RECORD_LOST:
            errors.append("lost_record")
        elif kind == PERF_RECORD_LOST_SAMPLES:
            errors.append("lost_samples_record")
        elif kind != PERF_RECORD_SWITCH:
            errors.append("unknown_record_type")
        else:
            pid, tid, time_ns, cpu, _res = SWITCH_BODY.unpack_from(data, offset + 8)
            is_out = bool(misc & MISC_SWITCH_OUT)
            if not is_out and misc & MISC_SWITCH_OUT_PREEMPT:
                errors.append("illegal_preempt_on_in")
            records.append({"pid": pid, "tid": tid, "time_ns": time_ns, "cpu": cpu, "is_out": is_out})
            if is_out:
                if open_out is not None:
                    errors.append("unpaired_out")
                open_out = time_ns
            else:
                if open_out is None:
                    errors.append("unpaired_in")
                else:
                    if time_ns == open_out:
                        errors.append("zero_length_span")
                    else:
                        spans.append((open_out, time_ns))
                    open_out = None
        offset += size
    if open_out is not None:
        errors.append("unpaired_out")
    return records, sorted(set(errors)), spans


def evaluate(case_dir):
    with open(os.path.join(case_dir, "metadata.json"), encoding="utf-8") as stream:
        meta = json.load(stream)
    with open(os.path.join(case_dir, "raw.bin"), "rb") as stream:
        data = stream.read()
    records, structural, spans = decode(data)

    envelope = []
    if type(meta.get("captured_bytes")) is not int:
        envelope.append("captured_bytes_not_int")
    elif meta["captured_bytes"] != len(data):
        envelope.append("raw_length_mismatch")
    if type(meta.get("owner_tid")) is not int:
        envelope.append("owner_tid_not_int")
    if meta.get("collector_complete") is not True:
        envelope.append("collector_incomplete")
    if meta.get("collector_errors"):
        envelope.append("collector_errors")
    # Contract sync: reader_policy must be the Linux plain int 0 (SCHED_OTHER); a string
    # spelling such as "SCHED_OTHER" is a type violation.
    if type(meta.get("reader_policy")) is not int or meta.get("reader_policy") != 0:
        envelope.append("reader_policy_not_int0")
    lifecycle = meta.get("lifecycle") or {}
    for key in ("disable_ok", "reader_joined", "munmap_ok", "close_ok"):
        if lifecycle.get(key) is not True:
            envelope.append("lifecycle_" + key)
    # checksum_ok = the metadata integer fields are the right type and the declared byte
    # count matches the raw file exactly. It is independent of completeness/collector errors.
    checksum_ok = not ({"captured_bytes_not_int", "raw_length_mismatch",
                        "owner_tid_not_int"} & set(envelope))

    owner_tid = meta.get("owner_tid")
    identity, last_time = [], None
    for item in records:
        if item["tid"] != owner_tid:
            identity.append("foreign_tid")
        if item["time_ns"] <= 0:
            identity.append("nonpositive_time")
        if last_time is not None and item["time_ns"] <= last_time:
            identity.append("nonincreasing_time")
        last_time = item["time_ns"]

    windows_errors, intersections = [], None
    windows_path = os.path.join(case_dir, "windows.json")
    if os.path.isfile(windows_path):
        with open(windows_path, encoding="utf-8") as stream:
            doc = json.load(stream)
        if doc.get("boot_id") != meta.get("boot_id"):
            windows_errors.append("windows_boot_mismatch")
        if (doc.get("owner_tid") != meta.get("owner_tid")
                or doc.get("owner_pid") != meta.get("owner_pid")):
            windows_errors.append("windows_owner_mismatch")
        if doc.get("clock_id") != meta.get("clock_id"):
            windows_errors.append("windows_clock_mismatch")
        intersections = []
        for window in doc.get("windows", []):
            start, end = window["start_ns"], window["end_ns"]
            if end < start:
                windows_errors.append("windows_reversed")
            total = 0
            for span_start, span_end in spans:
                total += max(0, min(span_end, end) - max(span_start, start))
            intersections.append(total)

    all_errors = sorted(set(envelope + structural + identity + windows_errors))
    return {"rejected": bool(all_errors), "checksum_ok": checksum_ok,
            "pairs": 0 if all_errors else len(spans), "errors": all_errors,
            "intersections_ns": intersections}


def check():
    index_path = os.path.join(FIXTURES, "index.json")
    if not os.path.isfile(index_path):
        print("FAIL index.json missing; run without --check first", file=sys.stderr)
        return 1
    with open(index_path, encoding="utf-8") as stream:
        index = json.load(stream)
    bad = 0
    for entry in index["cases"]:
        case_dir = os.path.join(FIXTURES, entry["case"])
        for filename, want in entry["files"].items():
            with open(os.path.join(case_dir, filename), "rb") as stream:
                got = digest(stream.read())
            if got != want["sha256"]:
                print("FAIL digest %s/%s" % (entry["case"], filename), file=sys.stderr)
                bad += 1
        observed = evaluate(case_dir)
        with open(os.path.join(case_dir, "expected.json"), encoding="utf-8") as stream:
            expected = json.load(stream)
        comparable = {key: expected[key] for key in ASSERT_KEYS if key in expected}
        observed_comparable = {key: observed[key] for key in comparable}
        if comparable != observed_comparable:
            print("FAIL expectation %s\n  declared=%s\n  observed=%s"
                  % (entry["case"], comparable, observed_comparable), file=sys.stderr)
            bad += 1
    print("cases=%d  mismatches=%d" % (len(index["cases"]), bad))
    return 1 if bad else 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="re-decode the fixtures on disk and re-assert expected.json")
    args = parser.parse_args()
    if args.check:
        return check()
    index = generate()
    print("wrote %d fixtures under %s" % (len(index["cases"]), FIXTURES))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
