"""Pure tests for the read-only snapshot comparison tool.

The two snapshots are generated by the real capture tool over a temporary
/proc-shaped tree, reusing the capture tests' fixtures by import (the capture
module and its tests are not modified). These tests are NOT native evidence:
no real process is sampled.

Delta numbers below are hand-computed from the fixture counters.
"""
import hashlib
import json
from pathlib import Path
import shutil
import sys

import pytest

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools.capture_owned_scheduling import OwnedSchedulingCapture
from tools.compare_owned_scheduling import SnapshotComparison
from validation.test_owned_scheduling import (
    ChurnReader,
    build_proc_tree,
    make_children,
    write,
)


class TickingClock:
    """Strictly increasing monotonic clock shared across both captures."""

    def __init__(self):
        self.ns = 0

    def __call__(self):
        self.ns += 1_000_000
        return {"wall_utc": "2026-09-13T00:00:00+00:00",
                "monotonic_ns": self.ns, "boottime_ns": None}


def snapshot(proc_root, children, path, clock, phase, reader=None):
    capture = OwnedSchedulingCapture(
        children, path, phase=phase, proc_root=proc_root, clock_ticks=100,
        now=clock, reader=reader)
    return capture.capture()


def thread(tid, *, utime=10, stime=20, schedstat=(111, 222, 3),
           start_ticks=500, rt_priority=40, policy=1,
           sched="policy : 1\nprio : 59\n"):
    return {"tid": tid, "comm": f"t{tid}", "state": "S",
            "start_ticks": start_ticks, "utime": utime, "stime": stime,
            "schedstat": schedstat, "rt_priority": rt_priority,
            "policy": policy, "sched": sched}


def base_tree(root, threads, *, schedstats="1", boot_id="boot-abc"):
    proc = build_proc_tree(root, [
        {"pid": 100, "pgid": 100, "start_ticks": 500, "comm": "worker",
         "threads": threads}], schedstats=schedstats)
    if boot_id is not None:
        write(proc / "sys/kernel/random/boot_id", boot_id + "\n")
    return proc


def set_switches(proc_root, tid, voluntary, nonvoluntary, cpus="0-7"):
    write(proc_root / "100" / "task" / str(tid) / "status",
          f"Cpus_allowed_list:\t{cpus}\n"
          f"voluntary_ctxt_switches:\t{voluntary}\n"
          f"nonvoluntary_ctxt_switches:\t{nonvoluntary}\n")


def worker_children(tmp_path, extra=None):
    entries = {"worker-a": {"identity": {"pid": 100, "pgid": 100,
                                         "start_ticks": 500,
                                         "argv": ["/usr/bin/python3", "-m", "worker"]}}}
    if extra:
        entries.update(extra)
    return make_children(tmp_path, entries)


def run_compare(tmp_path, proc_b, proc_a, children, *, reader_after=None,
                output="delta.json"):
    clock = TickingClock()
    snapshot(proc_b, children, tmp_path / "before.json", clock, "before")
    snapshot(proc_a, children, tmp_path / "after.json", clock, "after",
             reader=reader_after)
    return SnapshotComparison(tmp_path / "before.json", tmp_path / "after.json",
                              tmp_path / output).compare()


def test_bound_comparison_hand_computed_deltas(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [
        thread(100, utime=10, stime=20, schedstat=(111, 222, 3)),
        thread(101, utime=30, stime=40, schedstat=(50, 60, 2))])
    proc_a = base_tree(tmp_path / "a", [
        thread(100, utime=25, stime=24, schedstat=(311, 322, 8)),
        thread(101, utime=30, stime=40, schedstat=(50, 60, 2))])
    set_switches(proc_b, 100, 3, 0)
    set_switches(proc_b, 101, 1, 1)
    set_switches(proc_a, 100, 9, 2)
    set_switches(proc_a, 101, 1, 1)

    result = run_compare(tmp_path, proc_b, proc_a, children)

    assert result["schema"] == "wksim.owned-scheduling-comparison.v1"
    assert result["binding"]["status"] == "bound"
    assert result["binding"]["reasons"] == []
    assert result["binding"]["monotonic_delta_ns"] > 0
    assert result["performance_verdict"] == "not_evaluated"
    assert result["attribution"] == "not_evaluated"

    role = result["roles"]["worker-a"]
    assert role["status"] == "compared"
    assert role["threads_compared"] == 2
    assert role["threads_unavailable"] == 0

    rows = {row["tid"]: row for row in role["compared_threads"]}
    assert rows[100]["delta"] == {
        "utime_ticks": 15, "stime_ticks": 4, "run_ns": 200,
        "runqueue_ns": 100, "timeslices": 5,
        "voluntary_ctxt_switches": 6, "nonvoluntary_ctxt_switches": 2}
    assert rows[100]["negative_counters"] == []
    assert rows[100]["delta_unavailable"] == {}
    transitions = rows[100]["transitions"]
    assert transitions["rt_priority"] == {"before": 40, "after": 40,
                                          "changed": False}
    assert transitions["kernel_prio"]["before"] == 59
    assert "not" in transitions["kernel_prio"]["note"].lower()
    assert transitions["cpus_allowed_list"]["changed"] is False

    # A genuinely unchanged counter yields 0, not null.
    assert rows[101]["delta"] == {
        "utime_ticks": 0, "stime_ticks": 0, "run_ns": 0, "runqueue_ns": 0,
        "timeslices": 0, "voluntary_ctxt_switches": 0,
        "nonvoluntary_ctxt_switches": 0}


def test_children_sha_mismatch_unbinds_and_writes_report(tmp_path):
    worker_children(tmp_path)  # children-start.json (before)
    children_b = tmp_path / "children-b.json"
    write(children_b, json.dumps({
        "worker-a": {"identity": {"pid": 100, "pgid": 100, "start_ticks": 500,
                                  "argv": ["/usr/bin/python3", "-m", "other"]}}}))
    proc = base_tree(tmp_path / "b", [thread(100)])
    clock = TickingClock()
    snapshot(proc, tmp_path / "children-start.json", tmp_path / "before.json",
             clock, "before")
    snapshot(proc, children_b, tmp_path / "after.json", clock, "after")

    result = SnapshotComparison(tmp_path / "before.json", tmp_path / "after.json",
                                tmp_path / "delta.json").compare()

    assert result["binding"]["status"] == "unbound"
    assert "children_sha256_mismatch" in result["binding"]["reasons"]
    assert result["roles"] == {}
    assert (tmp_path / "delta.json").exists()
    assert result["performance_verdict"] == "not_evaluated"


def test_boot_id_change_unbinds(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [thread(100)], boot_id="boot-abc")
    proc_a = base_tree(tmp_path / "a", [thread(100)], boot_id="boot-xyz")
    result = run_compare(tmp_path, proc_b, proc_a, children)

    assert result["binding"]["status"] == "unbound"
    assert "boot_id_mismatch" in result["binding"]["reasons"]
    assert result["roles"] == {}


def test_boot_id_unavailable_unbinds(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [thread(100)])
    proc_a = base_tree(tmp_path / "a", [thread(100)])
    (proc_a / "sys/kernel/random/boot_id").unlink()
    result = run_compare(tmp_path, proc_b, proc_a, children)

    assert result["binding"]["status"] == "unbound"
    assert "boot_id_unavailable" in result["binding"]["reasons"]


def test_thread_reuse_is_not_stitched(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [thread(100, start_ticks=500)])
    proc_a = base_tree(tmp_path / "a", [thread(100, start_ticks=501)])
    result = run_compare(tmp_path, proc_b, proc_a, children)

    role = result["roles"]["worker-a"]
    assert role["status"] == "compared"
    assert role["threads_compared"] == 0
    assert role["threads_unavailable"] == 1
    entry = role["unavailable_threads"][0]
    assert entry["unavailable_reason"] == "thread_reuse_not_stitched"
    assert entry["start_ticks_before"] == 500
    assert entry["start_ticks_after"] == 501
    assert "delta" not in entry


def test_schedstats_disabled_yields_null_runqueue(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [thread(100, schedstat=(111, 222, 3))],
                       schedstats="1")
    proc_a = base_tree(tmp_path / "a", [thread(100, schedstat=(311, 322, 8))],
                       schedstats="0")
    result = run_compare(tmp_path, proc_b, proc_a, children)

    delta = result["roles"]["worker-a"]["compared_threads"][0]["delta"]
    assert delta["run_ns"] == 200
    assert delta["runqueue_ns"] is None
    assert delta["runqueue_ns"] != 0
    assert delta["timeslices"] is None
    reasons = result["roles"]["worker-a"]["compared_threads"][0]["delta_unavailable"]
    assert "sched_schedstats_disabled" in reasons["runqueue_ns"]
    assert "after=" in reasons["runqueue_ns"]


def test_negative_counter_delta_is_flagged_not_clamped(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [
        thread(100, utime=30, stime=20, schedstat=(311, 222, 3))])
    proc_a = base_tree(tmp_path / "a", [
        thread(100, utime=10, stime=20, schedstat=(100, 222, 3))])
    set_switches(proc_b, 100, 9, 0)
    set_switches(proc_a, 100, 3, 0)
    result = run_compare(tmp_path, proc_b, proc_a, children)

    entry = result["roles"]["worker-a"]["compared_threads"][0]
    assert entry["delta"]["utime_ticks"] is None
    assert entry["delta"]["run_ns"] is None
    assert entry["delta"]["voluntary_ctxt_switches"] is None
    assert entry["delta"]["stime_ticks"] == 0
    assert set(entry["negative_counters"]) == {
        "utime_ticks", "run_ns", "voluntary_ctxt_switches"}
    for name in entry["negative_counters"]:
        assert entry["delta_unavailable"][name] == "negative_counter_delta"
        assert entry["delta"][name] is None  # never clamped to 0


def test_thread_added_and_removed_are_null_with_reason(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [thread(100), thread(101)])
    proc_a = base_tree(tmp_path / "a", [thread(100), thread(102)])
    result = run_compare(tmp_path, proc_b, proc_a, children)

    role = result["roles"]["worker-a"]
    assert role["threads_compared"] == 1
    assert [row["tid"] for row in role["compared_threads"]] == [100]
    reasons = {row["tid"]: row["unavailable_reason"]
               for row in role["unavailable_threads"]}
    assert reasons == {101: "thread_vanished_after",
                       102: "thread_added_after"}


def test_partial_side_marks_role_partial(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [thread(100)])
    proc_a = base_tree(tmp_path / "a", [thread(100)])
    result = run_compare(tmp_path, proc_b, proc_a, children,
                         reader_after=ChurnReader(proc_a))

    role = result["roles"]["worker-a"]
    assert role["status"] == "partial"
    assert role["partial_reason"] == "process_partial_in_one_snapshot"
    assert role["after_status"] == "partial"
    assert role["threads_compared"] == 1
    assert role["unavailable_threads"][0]["tid"] == 424242


def test_process_vanished_in_after_is_unavailable(tmp_path):
    children = worker_children(tmp_path)
    proc_b = base_tree(tmp_path / "b", [thread(100)])
    proc_a = base_tree(tmp_path / "a", [thread(100)])
    shutil.rmtree(proc_a / "100")
    result = run_compare(tmp_path, proc_b, proc_a, children)

    role = result["roles"]["worker-a"]
    assert role["status"] == "unavailable"
    assert role["unavailable_reason"] == "process_unavailable"
    assert role["before_status"] == "captured"
    assert role["after_status"] == "unavailable"
    assert role["after_reason"] == "vanished_before_read"


def test_output_exclusive_and_inputs_untouched(tmp_path):
    children = worker_children(tmp_path)
    proc = base_tree(tmp_path / "b", [thread(100)])
    clock = TickingClock()
    before = tmp_path / "before.json"
    after = tmp_path / "after.json"
    snapshot(proc, children, before, clock, "before")
    snapshot(proc, children, after, clock, "after")
    before_sha = hashlib.sha256(before.read_bytes()).hexdigest()
    after_sha = hashlib.sha256(after.read_bytes()).hexdigest()

    output = tmp_path / "delta.json"
    SnapshotComparison(before, after, output).compare()
    first = output.read_bytes()
    with pytest.raises(FileExistsError):
        SnapshotComparison(before, after, output).compare()

    assert output.read_bytes() == first
    assert hashlib.sha256(before.read_bytes()).hexdigest() == before_sha
    assert hashlib.sha256(after.read_bytes()).hexdigest() == after_sha


def test_unexpected_snapshot_schema_is_rejected(tmp_path):
    children = worker_children(tmp_path)
    proc = base_tree(tmp_path / "b", [thread(100)])
    snapshot(proc, children, tmp_path / "before.json", TickingClock(), "before")
    bad = tmp_path / "after.json"
    write(bad, json.dumps({"schema": "other"}))

    with pytest.raises(ValueError):
        SnapshotComparison(tmp_path / "before.json", bad,
                           tmp_path / "delta.json").compare()


def mutate(path, edit):
    document = json.loads(path.read_text(encoding="utf-8"))
    edit(document)
    write(path, json.dumps(document))


def make_pair(tmp_path, *, sb="1", sa="1", bb="boot-abc", ba="boot-abc",
              t100b=None, t100a=None):
    children = worker_children(tmp_path)
    pb = base_tree(tmp_path / "b", [t100b or thread(100)], schedstats=sb,
                   boot_id=bb)
    pa = base_tree(tmp_path / "a", [t100a or thread(100)], schedstats=sa,
                   boot_id=ba)
    clock = TickingClock()
    snapshot(pb, children, tmp_path / "before.json", clock, "before")
    snapshot(pa, children, tmp_path / "after.json", clock, "after")
    return tmp_path / "before.json", tmp_path / "after.json"


def compare_pair(before, after, output="delta.json"):
    return SnapshotComparison(before, after, before.parent / output).compare()


@pytest.mark.parametrize("value", ["xyz", 123, None])
def test_invalid_children_sha_unbinds(tmp_path, value):
    before, after = make_pair(tmp_path)

    def edit(document):
        if value is None:
            document["children"].pop("sha256", None)
        else:
            document["children"]["sha256"] = value

    mutate(after, edit)
    result = compare_pair(before, after)

    assert result["binding"]["status"] == "unbound"
    assert "children_sha256_unavailable" in result["binding"]["reasons"]
    assert result["roles"] == {}


@pytest.mark.parametrize("value", ["", 123, "   ", None])
def test_invalid_boot_id_unbinds(tmp_path, value):
    before, after = make_pair(tmp_path)

    def edit(document):
        if value is None:
            document["host"].pop("boot_id", None)
        else:
            document["host"]["boot_id"] = value

    mutate(after, edit)
    result = compare_pair(before, after)

    assert result["binding"]["status"] == "unbound"
    assert "boot_id_unavailable" in result["binding"]["reasons"]


@pytest.mark.parametrize("value", [-1, True, "5", None, 1.5])
def test_invalid_monotonic_unbinds(tmp_path, value):
    before, after = make_pair(tmp_path)

    def edit(document):
        if value is None:
            document["captured"].pop("monotonic_ns", None)
        else:
            document["captured"]["monotonic_ns"] = value

    mutate(after, edit)
    result = compare_pair(before, after)

    assert result["binding"]["status"] == "unbound"
    assert "monotonic_unavailable" in result["binding"]["reasons"]


def test_equal_monotonic_is_not_increasing(tmp_path):
    before, after = make_pair(tmp_path)
    mutate(after, lambda doc: doc["captured"].__setitem__(
        "monotonic_ns", json.loads(before.read_text())["captured"]["monotonic_ns"]))
    result = compare_pair(before, after)
    assert result["binding"]["status"] == "unbound"
    assert "monotonic_not_increasing" in result["binding"]["reasons"]


@pytest.mark.parametrize("side", ["both", "before", "after"])
def test_missing_expected_identity_is_not_a_match(tmp_path, side):
    before, after = make_pair(tmp_path)

    def drop(document):
        document["procs"]["worker-a"].pop("expected", None)

    if side in ("both", "before"):
        mutate(before, drop)
    if side in ("both", "after"):
        mutate(after, drop)
    result = compare_pair(before, after)

    assert result["binding"]["status"] == "bound"
    role = result["roles"]["worker-a"]
    assert role["status"] == "unavailable"
    assert role["unavailable_reason"] == "identity_unavailable"
    assert "compared_threads" not in role


@pytest.mark.parametrize("value", [None, "500", True, 500.0])
def test_missing_or_invalid_thread_start_ticks_not_matched(tmp_path, value):
    before, after = make_pair(tmp_path)

    def edit(document):
        for row in document["procs"]["worker-a"]["threads"]:
            if value is None:
                row.pop("start_ticks", None)
            else:
                row["start_ticks"] = value

    mutate(before, edit)
    mutate(after, edit)
    result = compare_pair(before, after)

    role = result["roles"]["worker-a"]
    assert role["threads_compared"] == 0
    assert role["unavailable_threads"][0]["unavailable_reason"] == \
        "thread_identity_unavailable"


def test_invalid_thread_tid_is_reported(tmp_path):
    before, after = make_pair(tmp_path)
    mutate(before, lambda doc: doc["procs"]["worker-a"]["threads"][0].__setitem__(
        "tid", "100"))
    result = compare_pair(before, after)

    role = result["roles"]["worker-a"]
    reasons = [row["unavailable_reason"] for row in role["unavailable_threads"]]
    assert "thread_tid_invalid_before" in reasons
    assert "thread_added_after" in reasons
    assert role["threads_compared"] == 0


@pytest.mark.parametrize("side", ["before", "after"])
@pytest.mark.parametrize("value", ["0", None, "unreadable"])
def test_host_flag_contradiction_nulls_wait_and_keeps_run(tmp_path, side, value):
    before, after = make_pair(
        tmp_path, t100b=thread(100, schedstat=(111, 222, 3)),
        t100a=thread(100, schedstat=(311, 322, 8)))

    def edit(document):
        if value is None:
            document["host"].pop("sched_schedstats", None)
        else:
            document["host"]["sched_schedstats"] = value

    mutate(before if side == "before" else after, edit)
    result = compare_pair(before, after)

    assert result["binding"]["status"] == "bound"
    entry = result["roles"]["worker-a"]["compared_threads"][0]
    assert entry["delta"]["run_ns"] == 200          # CPU run delta is kept
    assert entry["delta"]["runqueue_ns"] is None
    assert entry["delta"]["runqueue_ns"] != 0
    assert entry["delta"]["timeslices"] is None
    reason = entry["delta_unavailable"]["runqueue_ns"]
    assert "host_sched_schedstats_not_enabled" in reason
    assert f"{side}=" in reason


def test_row_flag_true_alone_is_not_trusted_when_host_disabled(tmp_path):
    # Rows still report runqueue_counters_valid=True, host disagrees.
    before, after = make_pair(
        tmp_path, t100b=thread(100, schedstat=(111, 222, 3)),
        t100a=thread(100, schedstat=(311, 322, 8)))
    mutate(after, lambda doc: doc["host"].__setitem__("sched_schedstats", "0"))
    row_flag = json.loads(after.read_text())["procs"]["worker-a"]["threads"][0]
    assert row_flag["schedstat"]["runqueue_counters_valid"] is True

    result = compare_pair(before, after)
    entry = result["roles"]["worker-a"]["compared_threads"][0]
    assert entry["delta"]["run_ns"] == 200
    assert entry["delta"]["runqueue_ns"] is None
    assert entry["delta"]["timeslices"] is None
    assert "host_sched_schedstats_not_enabled" in \
        entry["delta_unavailable"]["runqueue_ns"]


@pytest.mark.parametrize("field,container", [
    ("utime_ticks", "stat"), ("run_ns", "schedstat"),
    ("runqueue_ns", "schedstat"), ("timeslices", "schedstat"),
])
@pytest.mark.parametrize("bad", [True, "25", 25.5, -1])
@pytest.mark.parametrize("side", ["before", "after"])
def test_malformed_counter_is_unavailable_without_losing_other_metrics(
        tmp_path, field, container, bad, side):
    before, after = make_pair(tmp_path)
    mutate(before if side == "before" else after,
           lambda doc: doc["procs"]["worker-a"]["threads"][0][container].__setitem__(field, bad))
    result = compare_pair(before, after)
    row = result["roles"]["worker-a"]["compared_threads"][0]
    assert result["binding"]["status"] == "bound"
    assert row["delta"][field] is None
    assert row["delta_unavailable"][field] == "invalid_counter_value"
    assert row["delta"]["stime_ticks"] is not None


def test_string_validity_flag_does_not_enable_runqueue(tmp_path):
    before, after = make_pair(tmp_path)
    mutate(after, lambda doc: doc["procs"]["worker-a"]["threads"][0]["schedstat"].__setitem__(
        "runqueue_counters_valid", "false"))
    row = compare_pair(before, after)["roles"]["worker-a"]["compared_threads"][0]
    assert row["delta"]["runqueue_ns"] is None
    assert row["delta"]["run_ns"] is not None
