import ast,base64,json,pathlib,subprocess
root=pathlib.Path(__file__).resolve().parent
assert not (root/'read-fault-receipt.json').exists()
t=ast.parse((root/'run_checks.py').read_text())
pre=next(ast.literal_eval(n.value) for n in t.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id=='pre')
checks=[]
for distro in ['Ubuntu-22.04','RflySim-20.04']:
 r=subprocess.run(['wsl.exe','-d',distro,'-u','root','--','python3','-'],input=pre,capture_output=True,text=True,timeout=45)
 assert r.returncode==0,r.stderr
 c=json.loads([x for x in r.stdout.splitlines() if x.startswith('{')][-1]);assert not c['found'],c
 checks.append(c)
(root/'read-fault-prechecks.json').write_bytes((json.dumps(checks,indent=2)+'\n').encode())
payload={'checks':checks,'prior':json.loads((root/'receipt.json').read_bytes()),'test_source':base64.b64encode((root/'counter_read_faults.c').read_bytes()).decode(),'consumer':base64.b64encode((root.parent/'ds-perf-stream-consumer-20260913-01/perf_stream_consumer.py').read_bytes()).decode()}
linux="import base64,hashlib,json,os,pathlib,signal,subprocess,time\nr=payload['prior'];root=pathlib.Path(r['directory'])\nboot=pathlib.Path('/proc/sys/kernel/random/boot_id').read_text().strip()\nassert all(c['boot_id']==boot and 0<=time.time()-c['checked_unix']<=60 and not c['found'] for c in payload['checks'])\nassert all(hashlib.sha256((root/n).read_bytes()).hexdigest()==h for n,h in r['source_sha256'].items())\noutdir=root/'counter-read-faults';outdir.mkdir(exist_ok=False)\n(outdir/'test.c').write_bytes(base64.b64decode(payload['test_source']))\n(outdir/'consumer.py').write_bytes(base64.b64decode(payload['consumer']))\nout={'boot_id':boot,'directory':str(outdir),'source_sha256':r['source_sha256'],'commands':[]}\ncommands=[['cc','-std=c11','-O2','-Wall','-Wextra','-Werror','-pthread','-I'+str(root),'-Wl,--wrap=read','-o',str(outdir/'test'),str(outdir/'test.c'),str(root/'wksim_perf_stream.c')],[str(outdir/'test'),str(outdir)]]\nfor argv in commands:\n p=subprocess.Popen(argv,stdout=subprocess.PIPE,stderr=subprocess.PIPE,text=True,start_new_session=True)\n try:stdout,stderr=p.communicate(timeout=20)\n except subprocess.TimeoutExpired:os.killpg(p.pid,signal.SIGKILL);stdout,stderr=p.communicate()\n row={'argv':argv,'pid':p.pid,'exit_code':p.returncode,'stdout':stdout,'stderr':stderr}\n try:os.killpg(p.pid,0);row['pgid_empty']=False\n except ProcessLookupError:row['pgid_empty']=True\n out['commands'].append(row)\n if p.returncode or not row['pgid_empty']:break\nout['metadata_checks']=[]\nif len(out['commands'])==2 and out['commands'][-1]['exit_code']==0:\n for mode in [1,2,3]:\n  meta=json.loads((outdir/('read-%d.meta.json'%mode)).read_bytes())\n  valid=(meta['kernel_lost_read_ok'] is (mode==1) and meta['kernel_lost_count']==(0 if mode==1 else None))\n  argv=['python3',str(outdir/'consumer.py'),'--raw',str(outdir/('read-%d.raw'%mode)),'--metadata',str(outdir/('read-%d.meta.json'%mode)),'--output',str(outdir/('decoded-%d.json'%mode)),'--require-kernel-counter']\n  audit=subprocess.run(argv,capture_output=True,text=True,timeout=10)\n  valid=valid and audit.returncode==(0 if mode==1 else 3)\n  out['metadata_checks'].append({'mode':mode,'passed':valid,'read_bytes':meta['kernel_lost_read_bytes'],'read_errno':meta['kernel_lost_read_errno'],'counter':meta['kernel_lost_count'],'consumer_exit_code':audit.returncode,'consumer_stderr':audit.stderr})\nout['boot_after']=pathlib.Path('/proc/sys/kernel/random/boot_id').read_text().strip()\nout['files']={p.name:base64.b64encode(p.read_bytes()).decode() for p in outdir.iterdir() if p.name.endswith(('.raw','.json'))}\n(outdir/'receipt.json').write_text(json.dumps(out,indent=2));print(json.dumps(out))\n"
script='import base64,json\npayload=json.loads(base64.b64decode('+repr(base64.b64encode(json.dumps(payload).encode()).decode())+'))\n'+linux
r=subprocess.run(['wsl.exe','-d','Ubuntu-22.04','-u','root','--','python3','-'],input=script,capture_output=True,text=True,timeout=60)
assert r.returncode==0,(r.stdout,r.stderr)
out=json.loads([x for x in r.stdout.splitlines() if x.startswith('{')][-1])
(root/'read-fault-receipt.json').write_bytes((json.dumps(out,indent=2)+'\n').encode())
capture=root/'counter-read-faults';capture.mkdir(exist_ok=False)
for name,raw in out['files'].items():(capture/name).write_bytes(base64.b64decode(raw))
print(json.dumps({k:v for k,v in out.items() if k!='files'}))
